"""ai runs

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-08 09:59:32.292579
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("hunt_id", sa.UUID(), nullable=True),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("hours_back", sa.Integer(), nullable=False),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("conclusion", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("saved_findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["hunt_id"], ["hunts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_runs_created_at"), "ai_runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_ai_runs_hunt_id"), "ai_runs", ["hunt_id"], unique=False)
    op.create_index(op.f("ix_ai_runs_tenant_id"), "ai_runs", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_runs_tenant_id"), table_name="ai_runs")
    op.drop_index(op.f("ix_ai_runs_hunt_id"), table_name="ai_runs")
    op.drop_index(op.f("ix_ai_runs_created_at"), table_name="ai_runs")
    op.drop_table("ai_runs")
    # ### end Alembic commands ###
