"""hunts

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 16:14:29.542224
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hunts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="DRAFT", nullable=False),
        sa.Column("time_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("conclusion", sa.Text(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hunts_tenant_id"), "hunts", ["tenant_id"], unique=False)
    op.create_table(
        "hunt_findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("hunt_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["hunt_id"], ["hunts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hunt_findings_hunt_id"), "hunt_findings", ["hunt_id"], unique=False)
    op.create_index(op.f("ix_hunt_findings_tenant_id"), "hunt_findings", ["tenant_id"], unique=False)
    op.create_table(
        "hunt_notes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("hunt_id", sa.UUID(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["hunt_id"], ["hunts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hunt_notes_hunt_id"), "hunt_notes", ["hunt_id"], unique=False)
    op.create_index(op.f("ix_hunt_notes_tenant_id"), "hunt_notes", ["tenant_id"], unique=False)
    op.create_table(
        "query_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("hunt_id", sa.UUID(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("query", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("took_ms", sa.Integer(), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["hunt_id"], ["hunts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_query_history_executed_at"), "query_history", ["executed_at"], unique=False)
    op.create_index(op.f("ix_query_history_hunt_id"), "query_history", ["hunt_id"], unique=False)
    op.create_index(op.f("ix_query_history_tenant_id"), "query_history", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_query_history_user_id"), "query_history", ["user_id"], unique=False)
    op.create_table(
        "saved_queries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("hunt_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("query", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["hunt_id"], ["hunts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_saved_queries_hunt_id"), "saved_queries", ["hunt_id"], unique=False)
    op.create_index(op.f("ix_saved_queries_tenant_id"), "saved_queries", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_saved_queries_tenant_id"), table_name="saved_queries")
    op.drop_index(op.f("ix_saved_queries_hunt_id"), table_name="saved_queries")
    op.drop_table("saved_queries")
    op.drop_index(op.f("ix_query_history_user_id"), table_name="query_history")
    op.drop_index(op.f("ix_query_history_tenant_id"), table_name="query_history")
    op.drop_index(op.f("ix_query_history_hunt_id"), table_name="query_history")
    op.drop_index(op.f("ix_query_history_executed_at"), table_name="query_history")
    op.drop_table("query_history")
    op.drop_index(op.f("ix_hunt_notes_tenant_id"), table_name="hunt_notes")
    op.drop_index(op.f("ix_hunt_notes_hunt_id"), table_name="hunt_notes")
    op.drop_table("hunt_notes")
    op.drop_index(op.f("ix_hunt_findings_tenant_id"), table_name="hunt_findings")
    op.drop_index(op.f("ix_hunt_findings_hunt_id"), table_name="hunt_findings")
    op.drop_table("hunt_findings")
    op.drop_index(op.f("ix_hunts_tenant_id"), table_name="hunts")
    op.drop_table("hunts")
    # ### end Alembic commands ###
