"""ioc hunting

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-08 13:35:33.429848
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ioc_allowlist",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("value", sa.String(length=2048), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "type", "value", name="uq_ioc_allow"),
    )
    op.create_index(op.f("ix_ioc_allowlist_tenant_id"), "ioc_allowlist", ["tenant_id"], unique=False)
    op.create_table(
        "ioc_feeds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("feed_type", sa.String(length=32), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("secrets_enc", sa.LargeBinary(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("interval_minutes", sa.Integer(), nullable=False),
        sa.Column("max_age_days", sa.Integer(), nullable=False),
        sa.Column("min_confidence", sa.Integer(), nullable=False),
        sa.Column("max_items", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=12), nullable=False),
        sa.Column("last_detail", sa.String(length=300), nullable=False),
        sa.Column("last_new", sa.Integer(), nullable=False),
        sa.Column("last_seen_total", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_ioc_feed_name"),
    )
    op.create_index(op.f("ix_ioc_feeds_tenant_id"), "ioc_feeds", ["tenant_id"], unique=False)
    op.create_table(
        "ioc_hunts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("ioc_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("lookback_days", sa.Integer(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_by", sa.UUID(), nullable=True),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("hunt_id", sa.UUID(), nullable=True),
        sa.Column("match_count", sa.Integer(), nullable=False),
        sa.Column("new_match_count", sa.Integer(), nullable=False),
        sa.Column("coverage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["hunt_id"], ["hunts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ioc_hunts_case_id"), "ioc_hunts", ["case_id"], unique=False)
    op.create_index(op.f("ix_ioc_hunts_created_at"), "ioc_hunts", ["created_at"], unique=False)
    op.create_index(op.f("ix_ioc_hunts_status"), "ioc_hunts", ["status"], unique=False)
    op.create_index(op.f("ix_ioc_hunts_tenant_id"), "ioc_hunts", ["tenant_id"], unique=False)
    op.create_table(
        "iocs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("feed_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("value", sa.String(length=2048), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("threat_type", sa.String(length=64), nullable=False),
        sa.Column("malware", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("reference", sa.String(length=500), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("techniques", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("status_reason", sa.String(length=300), nullable=False),
        sa.Column("validated_by", sa.UUID(), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("seen_count", sa.Integer(), nullable=False),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_hunted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["feed_id"], ["ioc_feeds.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["validated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "type", "value", name="uq_ioc"),
    )
    op.create_index(op.f("ix_iocs_case_id"), "iocs", ["case_id"], unique=False)
    op.create_index(op.f("ix_iocs_feed_id"), "iocs", ["feed_id"], unique=False)
    op.create_index(op.f("ix_iocs_first_seen"), "iocs", ["first_seen"], unique=False)
    op.create_index(op.f("ix_iocs_status"), "iocs", ["status"], unique=False)
    op.create_index(op.f("ix_iocs_tenant_id"), "iocs", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_iocs_type"), "iocs", ["type"], unique=False)
    op.create_table(
        "ioc_matches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("hunt_id", sa.UUID(), nullable=False),
        sa.Column("ioc_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("matched_field", sa.String(length=64), nullable=False),
        sa.Column("host", sa.String(length=256), nullable=False),
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["hunt_id"], ["ioc_hunts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ioc_id"], ["iocs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ioc_id", "event_id", name="uq_ioc_match"),
    )
    op.create_index(op.f("ix_ioc_matches_event_id"), "ioc_matches", ["event_id"], unique=False)
    op.create_index(op.f("ix_ioc_matches_hunt_id"), "ioc_matches", ["hunt_id"], unique=False)
    op.create_index(op.f("ix_ioc_matches_ioc_id"), "ioc_matches", ["ioc_id"], unique=False)
    op.create_index(op.f("ix_ioc_matches_tenant_id"), "ioc_matches", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ioc_matches_tenant_id"), table_name="ioc_matches")
    op.drop_index(op.f("ix_ioc_matches_ioc_id"), table_name="ioc_matches")
    op.drop_index(op.f("ix_ioc_matches_hunt_id"), table_name="ioc_matches")
    op.drop_index(op.f("ix_ioc_matches_event_id"), table_name="ioc_matches")
    op.drop_table("ioc_matches")
    op.drop_index(op.f("ix_iocs_type"), table_name="iocs")
    op.drop_index(op.f("ix_iocs_tenant_id"), table_name="iocs")
    op.drop_index(op.f("ix_iocs_status"), table_name="iocs")
    op.drop_index(op.f("ix_iocs_first_seen"), table_name="iocs")
    op.drop_index(op.f("ix_iocs_feed_id"), table_name="iocs")
    op.drop_index(op.f("ix_iocs_case_id"), table_name="iocs")
    op.drop_table("iocs")
    op.drop_index(op.f("ix_ioc_hunts_tenant_id"), table_name="ioc_hunts")
    op.drop_index(op.f("ix_ioc_hunts_status"), table_name="ioc_hunts")
    op.drop_index(op.f("ix_ioc_hunts_created_at"), table_name="ioc_hunts")
    op.drop_index(op.f("ix_ioc_hunts_case_id"), table_name="ioc_hunts")
    op.drop_table("ioc_hunts")
    op.drop_index(op.f("ix_ioc_feeds_tenant_id"), table_name="ioc_feeds")
    op.drop_table("ioc_feeds")
    op.drop_index(op.f("ix_ioc_allowlist_tenant_id"), table_name="ioc_allowlist")
    op.drop_table("ioc_allowlist")
    # ### end Alembic commands ###
