"""intel and mitre

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-07 17:00:19.793740
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mitre_tactics",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("shortname", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("shortname"),
    )
    op.create_table(
        "mitre_techniques",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("parent_id", sa.String(length=16), nullable=True),
        sa.Column("tactics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("url", sa.String(length=300), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["mitre_techniques.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mitre_techniques_parent_id"), "mitre_techniques", ["parent_id"], unique=False)
    op.create_table(
        "intel_entities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("value", sa.String(length=2048), nullable=False),
        sa.Column("watch_verdict", sa.String(length=12), nullable=True),
        sa.Column("watch_confidence", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("verdict", sa.String(length=12), nullable=False),
        sa.Column("score_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("last_enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "type", "value", name="uq_intel_entity"),
    )
    op.create_index(op.f("ix_intel_entities_tenant_id"), "intel_entities", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_intel_entities_type"), "intel_entities", ["type"], unique=False)
    op.create_table(
        "intel_providers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("secrets_enc", sa.LargeBinary(), nullable=True),
        sa.Column("last_status", sa.String(length=16), nullable=False),
        sa.Column("last_detail", sa.String(length=300), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "provider", name="uq_intel_provider"),
    )
    op.create_index(op.f("ix_intel_providers_tenant_id"), "intel_providers", ["tenant_id"], unique=False)
    op.create_table(
        "mitre_mappings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("technique_id", sa.String(length=16), nullable=False),
        sa.Column("object_type", sa.String(length=16), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=False),
        sa.Column("confidence", sa.String(length=8), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("evidence_event_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["technique_id"],
            ["mitre_techniques.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "technique_id", "object_type", "object_id", name="uq_mitre_mapping"),
    )
    op.create_index(op.f("ix_mitre_mappings_object_id"), "mitre_mappings", ["object_id"], unique=False)
    op.create_index(op.f("ix_mitre_mappings_technique_id"), "mitre_mappings", ["technique_id"], unique=False)
    op.create_index(op.f("ix_mitre_mappings_tenant_id"), "mitre_mappings", ["tenant_id"], unique=False)
    op.create_table(
        "intel_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("verdict", sa.String(length=12), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["entity_id"], ["intel_entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "provider", name="uq_intel_observation"),
    )
    op.create_index(op.f("ix_intel_observations_entity_id"), "intel_observations", ["entity_id"], unique=False)
    op.create_index(op.f("ix_intel_observations_tenant_id"), "intel_observations", ["tenant_id"], unique=False)
    op.create_table(
        "intel_relations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("src_id", sa.UUID(), nullable=False),
        sa.Column("dst_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["dst_id"], ["intel_entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["src_id"], ["intel_entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "src_id", "dst_id", "kind", name="uq_intel_relation"),
    )
    op.create_index(op.f("ix_intel_relations_dst_id"), "intel_relations", ["dst_id"], unique=False)
    op.create_index(op.f("ix_intel_relations_src_id"), "intel_relations", ["src_id"], unique=False)
    op.create_index(op.f("ix_intel_relations_tenant_id"), "intel_relations", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_intel_relations_tenant_id"), table_name="intel_relations")
    op.drop_index(op.f("ix_intel_relations_src_id"), table_name="intel_relations")
    op.drop_index(op.f("ix_intel_relations_dst_id"), table_name="intel_relations")
    op.drop_table("intel_relations")
    op.drop_index(op.f("ix_intel_observations_tenant_id"), table_name="intel_observations")
    op.drop_index(op.f("ix_intel_observations_entity_id"), table_name="intel_observations")
    op.drop_table("intel_observations")
    op.drop_index(op.f("ix_mitre_mappings_tenant_id"), table_name="mitre_mappings")
    op.drop_index(op.f("ix_mitre_mappings_technique_id"), table_name="mitre_mappings")
    op.drop_index(op.f("ix_mitre_mappings_object_id"), table_name="mitre_mappings")
    op.drop_table("mitre_mappings")
    op.drop_index(op.f("ix_intel_providers_tenant_id"), table_name="intel_providers")
    op.drop_table("intel_providers")
    op.drop_index(op.f("ix_intel_entities_type"), table_name="intel_entities")
    op.drop_index(op.f("ix_intel_entities_tenant_id"), table_name="intel_entities")
    op.drop_table("intel_entities")
    op.drop_index(op.f("ix_mitre_techniques_parent_id"), table_name="mitre_techniques")
    op.drop_table("mitre_techniques")
    op.drop_table("mitre_tactics")
    # ### end Alembic commands ###
