"""threat bulletins

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-08 14:53:58.830496
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mitre_software",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("alias_keys", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("technique_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("url", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mitre_software_name"), "mitre_software", ["name"], unique=False)
    op.create_table(
        "threats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("references", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mitre_id", sa.String(length=16), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("ioc_count", sa.Integer(), nullable=False),
        sa.Column("ioc_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seen_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("status_reason", sa.String(length=300), nullable=False),
        sa.Column("validated_by", sa.UUID(), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("last_hunted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["validated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "key", name="uq_threat_key"),
    )
    op.create_index(op.f("ix_threats_last_updated"), "threats", ["last_updated"], unique=False)
    op.create_index(op.f("ix_threats_name"), "threats", ["name"], unique=False)
    op.create_index(op.f("ix_threats_status"), "threats", ["status"], unique=False)
    op.create_index(op.f("ix_threats_tenant_id"), "threats", ["tenant_id"], unique=False)
    op.create_table(
        "threat_ioas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("threat_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("technique_id", sa.String(length=16), nullable=False),
        sa.Column("query_text", sa.String(length=1000), nullable=False),
        sa.Column("condition", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trend_query", sa.String(length=1000), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rule_id"], ["detection_rules.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["threat_id"], ["threats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("threat_id", "name", name="uq_threat_ioa"),
    )
    op.create_index(op.f("ix_threat_ioas_tenant_id"), "threat_ioas", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_threat_ioas_threat_id"), "threat_ioas", ["threat_id"], unique=False)
    op.create_table(
        "threat_ttps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("threat_id", sa.UUID(), nullable=False),
        sa.Column("technique_id", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("confidence", sa.String(length=6), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["threat_id"], ["threats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("threat_id", "technique_id", name="uq_threat_ttp"),
    )
    op.create_index(op.f("ix_threat_ttps_technique_id"), "threat_ttps", ["technique_id"], unique=False)
    op.create_index(op.f("ix_threat_ttps_tenant_id"), "threat_ttps", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_threat_ttps_threat_id"), "threat_ttps", ["threat_id"], unique=False)
    op.create_table(
        "ioc_signal_matches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("hunt_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=3), nullable=False),
        sa.Column("ref", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("host", sa.String(length=256), nullable=False),
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["hunt_id"], ["ioc_hunts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "ref", "event_id", name="uq_signal_match"),
    )
    op.create_index(op.f("ix_ioc_signal_matches_event_id"), "ioc_signal_matches", ["event_id"], unique=False)
    op.create_index(op.f("ix_ioc_signal_matches_hunt_id"), "ioc_signal_matches", ["hunt_id"], unique=False)
    op.create_index(op.f("ix_ioc_signal_matches_tenant_id"), "ioc_signal_matches", ["tenant_id"], unique=False)
    op.add_column("ioc_hunts", sa.Column("threat_id", sa.UUID(), nullable=True))
    op.add_column(
        "ioc_hunts",
        sa.Column(
            "signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")
        ),
    )
    op.add_column("ioc_hunts", sa.Column("signal_count", sa.Integer(), nullable=False, server_default="0"))
    op.create_index(op.f("ix_ioc_hunts_threat_id"), "ioc_hunts", ["threat_id"], unique=False)
    op.create_foreign_key(None, "ioc_hunts", "threats", ["threat_id"], ["id"], ondelete="SET NULL")
    op.add_column("iocs", sa.Column("threat_name", sa.String(length=200), nullable=False, server_default=""))
    op.add_column("iocs", sa.Column("threat_kind", sa.String(length=12), nullable=False, server_default=""))
    op.add_column("iocs", sa.Column("threat_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_iocs_threat_id"), "iocs", ["threat_id"], unique=False)
    op.create_foreign_key(None, "iocs", "threats", ["threat_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "iocs", type_="foreignkey")
    op.drop_index(op.f("ix_iocs_threat_id"), table_name="iocs")
    op.drop_column("iocs", "threat_id")
    op.drop_column("iocs", "threat_kind")
    op.drop_column("iocs", "threat_name")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "ioc_hunts", type_="foreignkey")
    op.drop_index(op.f("ix_ioc_hunts_threat_id"), table_name="ioc_hunts")
    op.drop_column("ioc_hunts", "signal_count")
    op.drop_column("ioc_hunts", "signals")
    op.drop_column("ioc_hunts", "threat_id")
    op.drop_index(op.f("ix_ioc_signal_matches_tenant_id"), table_name="ioc_signal_matches")
    op.drop_index(op.f("ix_ioc_signal_matches_hunt_id"), table_name="ioc_signal_matches")
    op.drop_index(op.f("ix_ioc_signal_matches_event_id"), table_name="ioc_signal_matches")
    op.drop_table("ioc_signal_matches")
    op.drop_index(op.f("ix_threat_ttps_threat_id"), table_name="threat_ttps")
    op.drop_index(op.f("ix_threat_ttps_tenant_id"), table_name="threat_ttps")
    op.drop_index(op.f("ix_threat_ttps_technique_id"), table_name="threat_ttps")
    op.drop_table("threat_ttps")
    op.drop_index(op.f("ix_threat_ioas_threat_id"), table_name="threat_ioas")
    op.drop_index(op.f("ix_threat_ioas_tenant_id"), table_name="threat_ioas")
    op.drop_table("threat_ioas")
    op.drop_index(op.f("ix_threats_tenant_id"), table_name="threats")
    op.drop_index(op.f("ix_threats_status"), table_name="threats")
    op.drop_index(op.f("ix_threats_name"), table_name="threats")
    op.drop_index(op.f("ix_threats_last_updated"), table_name="threats")
    op.drop_table("threats")
    op.drop_index(op.f("ix_mitre_software_name"), table_name="mitre_software")
    op.drop_table("mitre_software")
    # ### end Alembic commands ###
