"""detections

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-08 09:24:14.268478
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "detection_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("compiled", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("unsupported", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("techniques", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tactics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hunt_id", sa.UUID(), nullable=True),
        sa.Column("tests_passed", sa.Boolean(), nullable=True),
        sa.Column("tests_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_status", sa.String(length=12), nullable=False),
        sa.Column("last_run_error", sa.String(length=300), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["hunt_id"], ["hunts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_detection_rules_status"), "detection_rules", ["status"], unique=False)
    op.create_index(op.f("ix_detection_rules_tenant_id"), "detection_rules", ["tenant_id"], unique=False)
    op.create_table(
        "detection_alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("rule_title", sa.String(length=200), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rule_id"], ["detection_rules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_id", "event_id", name="uq_alert_rule_event"),
    )
    op.create_index(op.f("ix_detection_alerts_event_id"), "detection_alerts", ["event_id"], unique=False)
    op.create_index(op.f("ix_detection_alerts_event_timestamp"), "detection_alerts", ["event_timestamp"], unique=False)
    op.create_index(op.f("ix_detection_alerts_rule_id"), "detection_alerts", ["rule_id"], unique=False)
    op.create_index(op.f("ix_detection_alerts_status"), "detection_alerts", ["status"], unique=False)
    op.create_index(op.f("ix_detection_alerts_tenant_id"), "detection_alerts", ["tenant_id"], unique=False)
    op.create_table(
        "detection_rule_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=False),
        sa.Column("changed_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["changed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rule_id"], ["detection_rules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_id", "version", name="uq_rule_version"),
    )
    op.create_index(op.f("ix_detection_rule_versions_rule_id"), "detection_rule_versions", ["rule_id"], unique=False)
    op.create_index(
        op.f("ix_detection_rule_versions_tenant_id"), "detection_rule_versions", ["tenant_id"], unique=False
    )
    op.create_table(
        "detection_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("error", sa.String(length=300), nullable=False),
        sa.Column("matches", sa.Integer(), nullable=False),
        sa.Column("new_alerts", sa.Integer(), nullable=False),
        sa.Column("took_ms", sa.Integer(), nullable=False),
        sa.Column("sample_event_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rule_id"], ["detection_rules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_detection_runs_created_at"), "detection_runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_detection_runs_rule_id"), "detection_runs", ["rule_id"], unique=False)
    op.create_index(op.f("ix_detection_runs_tenant_id"), "detection_runs", ["tenant_id"], unique=False)
    op.create_table(
        "detection_test_cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("event", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expect_match", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rule_id"], ["detection_rules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_detection_test_cases_rule_id"), "detection_test_cases", ["rule_id"], unique=False)
    op.create_index(op.f("ix_detection_test_cases_tenant_id"), "detection_test_cases", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_detection_test_cases_tenant_id"), table_name="detection_test_cases")
    op.drop_index(op.f("ix_detection_test_cases_rule_id"), table_name="detection_test_cases")
    op.drop_table("detection_test_cases")
    op.drop_index(op.f("ix_detection_runs_tenant_id"), table_name="detection_runs")
    op.drop_index(op.f("ix_detection_runs_rule_id"), table_name="detection_runs")
    op.drop_index(op.f("ix_detection_runs_created_at"), table_name="detection_runs")
    op.drop_table("detection_runs")
    op.drop_index(op.f("ix_detection_rule_versions_tenant_id"), table_name="detection_rule_versions")
    op.drop_index(op.f("ix_detection_rule_versions_rule_id"), table_name="detection_rule_versions")
    op.drop_table("detection_rule_versions")
    op.drop_index(op.f("ix_detection_alerts_tenant_id"), table_name="detection_alerts")
    op.drop_index(op.f("ix_detection_alerts_status"), table_name="detection_alerts")
    op.drop_index(op.f("ix_detection_alerts_rule_id"), table_name="detection_alerts")
    op.drop_index(op.f("ix_detection_alerts_event_timestamp"), table_name="detection_alerts")
    op.drop_index(op.f("ix_detection_alerts_event_id"), table_name="detection_alerts")
    op.drop_table("detection_alerts")
    op.drop_index(op.f("ix_detection_rules_tenant_id"), table_name="detection_rules")
    op.drop_index(op.f("ix_detection_rules_status"), table_name="detection_rules")
    op.drop_table("detection_rules")
    # ### end Alembic commands ###
