"""cases assets datasources

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-07 16:28:04.631053
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("key", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=320), nullable=False),
        sa.Column("criticality", sa.String(length=16), server_default="MEDIUM", nullable=False),
        sa.Column("owner", sa.String(length=200), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("event_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "type", "key", name="uq_asset_identity"),
    )
    op.create_index(op.f("ix_assets_tenant_id"), "assets", ["tenant_id"], unique=False)
    op.create_table(
        "case_counters",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("last", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_table(
        "data_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("connector_type", sa.String(length=64), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("secrets_enc", sa.LargeBinary(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("ingest_key_hash", sa.String(length=64), nullable=True),
        sa.Column("health_status", sa.String(length=16), server_default="unknown", nullable=False),
        sa.Column("health_detail", sa.String(length=300), nullable=False),
        sa.Column("health_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_ingest_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("events_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cursor", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ingest_key_hash"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_datasource_name"),
    )
    op.create_index(op.f("ix_data_sources_tenant_id"), "data_sources", ["tenant_id"], unique=False)
    op.create_table(
        "cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.String(length=2), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=False),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column("hunt_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["assignee_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["hunt_id"], ["hunts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "number", name="uq_case_number"),
    )
    op.create_index(op.f("ix_cases_status"), "cases", ["status"], unique=False)
    op.create_index(op.f("ix_cases_tenant_id"), "cases", ["tenant_id"], unique=False)
    op.create_table(
        "case_activity",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_case_activity_case_id"), "case_activity", ["case_id"], unique=False)
    op.create_index(op.f("ix_case_activity_created_at"), "case_activity", ["created_at"], unique=False)
    op.create_index(op.f("ix_case_activity_tenant_id"), "case_activity", ["tenant_id"], unique=False)
    op.create_table(
        "case_assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "asset_id", name="uq_case_asset"),
    )
    op.create_index(op.f("ix_case_assets_asset_id"), "case_assets", ["asset_id"], unique=False)
    op.create_index(op.f("ix_case_assets_case_id"), "case_assets", ["case_id"], unique=False)
    op.create_index(op.f("ix_case_assets_tenant_id"), "case_assets", ["tenant_id"], unique=False)
    op.create_table(
        "case_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("added_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["added_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "event_id", name="uq_case_event"),
    )
    op.create_index(op.f("ix_case_evidence_case_id"), "case_evidence", ["case_id"], unique=False)
    op.create_index(op.f("ix_case_evidence_tenant_id"), "case_evidence", ["tenant_id"], unique=False)
    op.create_table(
        "case_iocs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("value", sa.String(length=2048), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.Column("context", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "type", "value", name="uq_case_ioc"),
    )
    op.create_index(op.f("ix_case_iocs_case_id"), "case_iocs", ["case_id"], unique=False)
    op.create_index(op.f("ix_case_iocs_tenant_id"), "case_iocs", ["tenant_id"], unique=False)
    op.create_table(
        "case_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "version", name="uq_case_report_version"),
    )
    op.create_index(op.f("ix_case_reports_case_id"), "case_reports", ["case_id"], unique=False)
    op.create_index(op.f("ix_case_reports_tenant_id"), "case_reports", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_case_reports_tenant_id"), table_name="case_reports")
    op.drop_index(op.f("ix_case_reports_case_id"), table_name="case_reports")
    op.drop_table("case_reports")
    op.drop_index(op.f("ix_case_iocs_tenant_id"), table_name="case_iocs")
    op.drop_index(op.f("ix_case_iocs_case_id"), table_name="case_iocs")
    op.drop_table("case_iocs")
    op.drop_index(op.f("ix_case_evidence_tenant_id"), table_name="case_evidence")
    op.drop_index(op.f("ix_case_evidence_case_id"), table_name="case_evidence")
    op.drop_table("case_evidence")
    op.drop_index(op.f("ix_case_assets_tenant_id"), table_name="case_assets")
    op.drop_index(op.f("ix_case_assets_case_id"), table_name="case_assets")
    op.drop_index(op.f("ix_case_assets_asset_id"), table_name="case_assets")
    op.drop_table("case_assets")
    op.drop_index(op.f("ix_case_activity_tenant_id"), table_name="case_activity")
    op.drop_index(op.f("ix_case_activity_created_at"), table_name="case_activity")
    op.drop_index(op.f("ix_case_activity_case_id"), table_name="case_activity")
    op.drop_table("case_activity")
    op.drop_index(op.f("ix_cases_tenant_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_status"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_data_sources_tenant_id"), table_name="data_sources")
    op.drop_table("data_sources")
    op.drop_table("case_counters")
    op.drop_index(op.f("ix_assets_tenant_id"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
